locus-app/grails-app/domain/edu/luc/Section.groovy
package edu.luc

import org.bson.types.ObjectId
/*
 * A section is a specific instance of a course.
 * It is identified by the course and also by a section id.
 * Users enroll in sections of courses. 
 */

class Section {

    ObjectId id
    String lucSectionId
    int courseNumber

    Course course
    int maxSeats
    int enrolled

    User professor
}

locus-app/grails-app/controllers/edu/luc/SectionController.groovy
package edu.luc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SectionController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Section.list(params), model:[sectionCount: Section.count()]
    }

    def show(Section section) {
        respond section
    }

    def create() {
        respond new Section(params)
    }

    @Transactional                            
    def save(Section section) {
        if (!section) {
            notFound()
            return
        }

        if (section.hasErrors()) {
            respond section.errors, view:'create'
            return
        }

        section.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'section.label', default: 'Section'), section.id])
                redirect section
            }
            '*' { respond section, [status: CREATED] }
        }
    }

    def edit(Section section) {
        respond section
    }

    @Transactional
    def update(Section section) {
        if (!section) {
            notFound()
            return
        }

        if (section.hasErrors()) {
            respond section.errors, view:'edit'
            return
        }

        section.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Section.label', default: 'Section'), section.id])
                redirect section
            }
            '*'{ respond section, [status: OK] }
        }
    }

    @Transactional
    def delete(Section section) {

        if (!section) {
            notFound()
            return
        }

        section.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Section.label', default: 'Section'), section.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'section.label', default: 'Section'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

locus-app/grails-app/views/section/_form.gsp
<%@ page import="edu.luc.Section" %>



<div class="fieldcontain ${hasErrors(bean: sectionInstance, field: 'course', 'error')} ">
	<label for="course">
		<g:message code="section.course.label" default="Course" />
		
	</label>
	<g:select id="course" name="course.id" from="${edu.luc.Course.list()}" optionKey="id" required="" value="${sectionInstance?.course?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sectionInstance, field: 'courseNumber', 'error')} ">
	<label for="courseNumber">
		<g:message code="section.courseNumber.label" default="Course Number" />
		
	</label>
	<g:field type="number" name="courseNumber" value="${sectionInstance.courseNumber}" />
</div>

<div class="fieldcontain ${hasErrors(bean: sectionInstance, field: 'lucSectionId', 'error')} ">
	<label for="lucSectionId">
		<g:message code="section.lucSectionId.label" default="Luc Section Id" />
		
	</label>
	<g:textField name="lucSectionId" value="${sectionInstance?.lucSectionId}" />
</div>

<div class="fieldcontain ${hasErrors(bean: sectionInstance, field: 'maxSeats', 'error')} ">
	<label for="maxSeats">
		<g:message code="section.maxSeats.label" default="Max Seats" />
		
	</label>
	<g:field type="number" name="maxSeats" value="${sectionInstance.maxSeats}" />
</div>

<div class="fieldcontain ${hasErrors(bean: sectionInstance, field: 'professor', 'error')} ">
	<label for="professor">
		<g:message code="section.professor.label" default="Professor" />
		
	</label>
	<g:select id="professor" name="professor.id" from="${edu.luc.User.list()}" optionKey="id" required="" value="${sectionInstance?.professor?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: sectionInstance, field: 'semester', 'error')} ">
	<label for="semester">
		<g:message code="section.semester.label" default="Semester" />
		
	</label>
	<g:select id="semester" name="semester.id" from="${edu.luc.Semester.list()}" optionKey="id" required="" value="${sectionInstance?.semester?.id}" class="many-to-one"/>
</div>

locus-app/grails-app/views/section/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'section.label', default: 'Section')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-section" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-section" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sectionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sectionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sectionInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

locus-app/grails-app/views/section/edit.gsp
<%@ page import="edu.luc.Section" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'section.label', default: 'Section')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-section" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-section" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sectionInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sectionInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sectionInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${sectionInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

locus-app/grails-app/views/section/index.gsp
<%@ page import="edu.luc.Section" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'section.label', default: 'Section')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-section" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-section" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="section.course.label" default="Course" /></th>
					
						<g:sortableColumn property="courseNumber" title="${message(code: 'section.courseNumber.label', default: 'Course Number')}" />
					
						<g:sortableColumn property="lucSectionId" title="${message(code: 'section.lucSectionId.label', default: 'Luc Section Id')}" />
					
						<g:sortableColumn property="maxSeats" title="${message(code: 'section.maxSeats.label', default: 'Max Seats')}" />
					
						<th><g:message code="section.professor.label" default="Professor" /></th>
					
						<th><g:message code="section.semester.label" default="Semester" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${sectionInstanceList}" status="i" var="sectionInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${sectionInstance.id}">${fieldValue(bean: sectionInstance, field: "course")}</g:link></td>
					
						<td>${fieldValue(bean: sectionInstance, field: "courseNumber")}</td>
					
						<td>${fieldValue(bean: sectionInstance, field: "lucSectionId")}</td>
					
						<td>${fieldValue(bean: sectionInstance, field: "maxSeats")}</td>
					
						<td>${fieldValue(bean: sectionInstance, field: "professor")}</td>
					
						<td>${fieldValue(bean: sectionInstance, field: "semester")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${sectionInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

locus-app/grails-app/views/section/show.gsp
<%@ page import="edu.luc.Section" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'section.label', default: 'Section')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-section" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-section" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list section">
			
				<g:if test="${sectionInstance?.course}">
				<li class="fieldcontain">
					<span id="course-label" class="property-label"><g:message code="section.course.label" default="Course" /></span>
					
						<span class="property-value" aria-labelledby="course-label"><g:link controller="course" action="show" id="${sectionInstance?.course?.id}">${sectionInstance?.course?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${sectionInstance?.courseNumber}">
				<li class="fieldcontain">
					<span id="courseNumber-label" class="property-label"><g:message code="section.courseNumber.label" default="Course Number" /></span>
					
						<span class="property-value" aria-labelledby="courseNumber-label"><g:fieldValue bean="${sectionInstance}" field="courseNumber"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sectionInstance?.lucSectionId}">
				<li class="fieldcontain">
					<span id="lucSectionId-label" class="property-label"><g:message code="section.lucSectionId.label" default="Luc Section Id" /></span>
					
						<span class="property-value" aria-labelledby="lucSectionId-label"><g:fieldValue bean="${sectionInstance}" field="lucSectionId"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sectionInstance?.maxSeats}">
				<li class="fieldcontain">
					<span id="maxSeats-label" class="property-label"><g:message code="section.maxSeats.label" default="Max Seats" /></span>
					
						<span class="property-value" aria-labelledby="maxSeats-label"><g:fieldValue bean="${sectionInstance}" field="maxSeats"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${sectionInstance?.professor}">
				<li class="fieldcontain">
					<span id="professor-label" class="property-label"><g:message code="section.professor.label" default="Professor" /></span>
					
						<span class="property-value" aria-labelledby="professor-label"><g:link controller="user" action="show" id="${sectionInstance?.professor?.id}">${sectionInstance?.professor?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${sectionInstance?.semester}">
				<li class="fieldcontain">
					<span id="semester-label" class="property-label"><g:message code="section.semester.label" default="Semester" /></span>
					
						<span class="property-value" aria-labelledby="semester-label"><g:link controller="semester" action="show" id="${sectionInstance?.semester?.id}">${sectionInstance?.semester?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:sectionInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${sectionInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>