locus-app/grails-app/domain/edu/luc/Semester.groovy
package edu.luc

import org.bson.types.ObjectId
/*
 * Courses are offered in different semesters. 
 * At Loyola these semesters take place during the 
 * Fall (Fall semester), Winter (J-term), Spring 
 * (Spring semester), or Summer (multiple Summer sessions).
 */

class Semester {

    ObjectId id

    Season season
    int year
}

locus-app/grails-app/controllers/edu/luc/SemesterController.groovy
package edu.luc



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SemesterController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Semester.list(params), model: [semesterCount: Semester.count()]
    }

    def show(Semester semester) {
        respond semester
    }

    def create() {
        respond new Semester(params)
    }

    @Transactional
    def save(Semester semester) {
        if (!semester) {
            notFound()
            return
        }

        if (semester.hasErrors()) {
            respond semester.errors, view: 'create'
            return
        }

        semester.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'semester.label', default: 'Semester'), semester.id])
                redirect semester
            }
            '*' { respond semester, [status: CREATED] }
        }
    }

    def edit(Semester semester) {
        respond semester
    }

    @Transactional
    def update(Semester semester) {
        if (!semester) {
            notFound()
            return
        }

        if (semester.hasErrors()) {
            respond semester.errors, view: 'edit'
            return
        }

        semester.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Semester.label', default: 'Semester'), semester.id])
                redirect semester
            }
            '*' { respond semester, [status: OK] }
        }
    }

    @Transactional
    def delete(Semester semester) {

        if (!semester) {
            notFound()
            return
        }

        semester.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Semester.label', default: 'Semester'), semester.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'semester.label', default: 'Semester'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

locus-app/grails-app/views/semester/_form.gsp
<%@ page import="edu.luc.Semester" %>



<div class="fieldcontain ${hasErrors(bean: semesterInstance, field: 'season', 'error')} ">
	<label for="season">
		<g:message code="semester.season.label" default="Season" />
		
	</label>
	<g:select name="season" from="${edu.luc.Season?.values()}" keys="${edu.luc.Season.values()*.name()}" required="" value="${semesterInstance?.season?.name()}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: semesterInstance, field: 'year', 'error')} ">
	<label for="year">
		<g:message code="semester.year.label" default="Year" />
		
	</label>
	<g:field type="number" name="year" value="${semesterInstance.year}" />
</div>

locus-app/grails-app/views/semester/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'semester.label', default: 'Semester')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-semester" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-semester" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${semesterInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${semesterInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:semesterInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

locus-app/grails-app/views/semester/edit.gsp
<%@ page import="edu.luc.Semester" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'semester.label', default: 'Semester')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-semester" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-semester" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${semesterInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${semesterInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:semesterInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${semesterInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

locus-app/grails-app/views/semester/index.gsp
<%@ page import="edu.luc.Semester" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'semester.label', default: 'Semester')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-semester" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-semester" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="season" title="${message(code: 'semester.season.label', default: 'Season')}" />
					
						<g:sortableColumn property="year" title="${message(code: 'semester.year.label', default: 'Year')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${semesterInstanceList}" status="i" var="semesterInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${semesterInstance.id}">${fieldValue(bean: semesterInstance, field: "season")}</g:link></td>
					
						<td>${fieldValue(bean: semesterInstance, field: "year")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${semesterInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

locus-app/grails-app/views/semester/show.gsp
<%@ page import="edu.luc.Semester" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'semester.label', default: 'Semester')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-semester" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-semester" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list semester">
			
				<g:if test="${semesterInstance?.season}">
				<li class="fieldcontain">
					<span id="season-label" class="property-label"><g:message code="semester.season.label" default="Season" /></span>
					
						<span class="property-value" aria-labelledby="season-label"><g:fieldValue bean="${semesterInstance}" field="season"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${semesterInstance?.year}">
				<li class="fieldcontain">
					<span id="year-label" class="property-label"><g:message code="semester.year.label" default="Year" /></span>
					
						<span class="property-value" aria-labelledby="year-label"><g:fieldValue bean="${semesterInstance}" field="year"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:semesterInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${semesterInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>